const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('api', {
  getSnapshot: () => ipcRenderer.invoke('get-snapshot'),
  openEditor: (file, id) => ipcRenderer.invoke('open-editor', file, id),
  saveSettings: s => ipcRenderer.invoke('save-settings', s),
  updateTask: (file, id, patch) => ipcRenderer.invoke('update-task', file, id, patch),
  addTask: (file, data) => ipcRenderer.invoke('add-task', file, data),
  addSubtask: (file, parentId, title) => ipcRenderer.invoke('add-subtask', file, parentId, title),
  toggleSubtask: (file, parentId, title) => ipcRenderer.invoke('toggle-subtask', file, parentId, title),
  complete: (id, file) => ipcRenderer.invoke('complete', id, file),
  deleteTask: (id, file) => ipcRenderer.invoke('delete-task', id, file),
  undoAction: token => ipcRenderer.invoke('undo-action', token),
  undoExpire: token => ipcRenderer.invoke('undo-expire', token),
  deleteSubtask: (file, parentId, title) => ipcRenderer.invoke('delete-subtask', file, parentId, title),
  uncomplete: (id, file) => ipcRenderer.invoke('uncomplete-task', id, file),
  moveTask: (file, id, dir) => ipcRenderer.invoke('move-task', file, id, dir),
  reorderTask: (file, id, beforeId) => ipcRenderer.invoke('reorder-task', file, id, beforeId),
  clearDoneAll: () => ipcRenderer.invoke('clear-done-all'),
  composeTask: data => ipcRenderer.invoke('compose-task', data),
  openNote: file => ipcRenderer.invoke('open-note', file),
  openShare: () => ipcRenderer.invoke('open-share'),
  exportMd: text => ipcRenderer.invoke('export-md', text),
  copyText: text => ipcRenderer.invoke('copy-text', text),
  onTasksChanged: cb => ipcRenderer.on('tasks-changed', () => cb()),
  onShowUndo: cb => ipcRenderer.on('show-undo', (_e, d) => cb(d)),
  onShowTab: cb => ipcRenderer.on('show-tab', (_e, tab) => cb(tab))
});
