const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('api', {
  getSnapshot: () => ipcRenderer.invoke('get-snapshot'),
  saveSettings: s => ipcRenderer.invoke('save-settings', s),
  resetSettings: () => ipcRenderer.invoke('reset-settings'),
  openOnboard: () => ipcRenderer.invoke('open-onboarding'),
  updateTask: (file, id, patch) => ipcRenderer.invoke('update-task', file, id, patch),
  toggleActive: (id, file) => ipcRenderer.invoke('toggle-active', id, file),
  addTask: (file, data) => ipcRenderer.invoke('add-task', file, data),
  addSubtask: (file, parentId, title, session) => ipcRenderer.invoke('add-subtask', file, parentId, title, session),
  toggleSubtask: (file, parentId, title, session) => ipcRenderer.invoke('toggle-subtask', file, parentId, title, session),
  subtaskPriority: (file, parentId, title, p, session) => ipcRenderer.invoke('subtask-priority', file, parentId, title, p, session),
  renameSubtask: (file, parentId, title, newTitle, session) => ipcRenderer.invoke('rename-subtask', file, parentId, title, newTitle, session),
  complete: (id, file) => ipcRenderer.invoke('complete', id, file),
  deleteTask: (id, file) => ipcRenderer.invoke('delete-task', id, file),
  undoAction: token => ipcRenderer.invoke('undo-action', token),
  undoExpire: token => ipcRenderer.invoke('undo-expire', token),
  deleteSubtask: (file, parentId, title, session) => ipcRenderer.invoke('delete-subtask', file, parentId, title, session),
  uncomplete: (id, file) => ipcRenderer.invoke('uncomplete-task', id, file),
  moveTask: (file, id, dir) => ipcRenderer.invoke('move-task', file, id, dir),
  reorderTask: (file, id, beforeId) => ipcRenderer.invoke('reorder-task', file, id, beforeId),
  clearDoneAll: () => ipcRenderer.invoke('clear-done-all'),
  composeTask: data => ipcRenderer.invoke('compose-task', data),
  openNote: file => ipcRenderer.invoke('open-note', file),
  openUpdate: () => ipcRenderer.invoke('open-update'),
  exportMd: text => ipcRenderer.invoke('export-md', text),
  copyText: text => ipcRenderer.invoke('copy-text', text),
  onWindowOpened: cb => ipcRenderer.on('window-opened', () => cb()), // opened / brought forward / restored → sort again
  onTasksChanged: cb => ipcRenderer.on('tasks-changed', () => cb()),
  onShowUndo: cb => ipcRenderer.on('show-undo', (_e, d) => cb(d)),
  onLangChanged: cb => ipcRenderer.on('lang-changed', (_e, lang) => cb(lang)),
  onShowTab: cb => ipcRenderer.on('show-tab', (_e, tab) => cb(tab)),
  onOpenPanel: cb => ipcRenderer.on('open-panel', (_e, p) => cb(p)) // the island's Edit / Share open the side panel here
});
